### ISSUE TITLE
[Feature Request] Add text images to images section if surrounded by fenced code block with correct syntax declaration.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#10]
I have a surprising amount of text-based images. I use these like regular images, so I'd like to be able to make them appear in the images section. To do this, I propose something really simple – the `text_image` fenced code block syntax declaration:

~~~markdown
```text_image
⠄⠄⠄⢰⣧⣼⣯⠄⣸⣠⣶⣶⣦⣾⠄⠄⠄⠄⡀⠄⢀⣿⣿⠄⠄⠄⢸⡇
⠄⠄⠄⣾⣿⠿⠿⠶⠿⢿⣿⣿⣿⣿⣦⣤⣄⢀⡅⢠⣾⣛⡉⠄⠄⠄⠸⢀
⠄⠄⢀⡋⣡⣴⣶⣶⡀⠄⠄⠙⢿⣿⣿⣿⣿⣿⣴⣿⣿⣿⢃⣤⣄⣀⣥⣿
⠄⠄⢸⣇⠻⣿⣿⣿⣧⣀⢀⣠⡌⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠿⣿⣿
⠄⢀⢸⣿⣷⣤⣤⣤⣬⣙⣛⢿⣿⣿⣿⣿⣿⣿⡿⣿⣿⡍⠄⠄⢀⣤⣄⠉
⠄⣼⣖⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⢇⣿⣿⡷⠶⠶⢿⣿⣿⠇
⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣿⣿⣿⡇⣿⣿⣿⣿⣿⣿⣷⣶⣥⣴
⢀⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⢸⣿⣦⣌⣛⣻⣿⣿⣧⠙⠛⠛⡭⠅⠒⠦⠭⣭⡻⣿⣿⣿⣿⣿⣿⣿⣿⡿
⠘⣿⣿⣿⣿⣿⣿⣿⣿⡆⠄⠄⠄⠄⠄⠄⠄⠄⠹⠈⢋⣽⣿⣿⣿⣿⣵⣾
⠄⠘⣿⣿⣿⣿⣿⣿⣿⣿⠄⣴⣿⣶⣄⠄⣴⣶⠄⢀⣾⣿⣿⣿⣿⣿⣿⠃
⠄⠄⠈⠻⣿⣿⣿⣿⣿⣿⡄⢻⣿⣿⣿⠄⣿⣿⡀⣾⣿⣿⣿⣿⣛⠛⠁⠄
⠄⠄⠄⠄⠈⠛⢿⣿⣿⣿⠁⠞⢿⣿⣿⡄⢿⣿⡇⣸⣿⣿⠿⠛⠁⠄⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠉⠻⣿⣿⣾⣦⡙⠻⣷⣾⣿⠃⠿⠋⠁⠄⠄⠄⠄⠄.
⣿⣿⣿⣶⣶⣮⣥⣒⠲⢮⣝⡿⣿⣿⡆⣿⡿⠃⠄⠄⠄⠄⠄⠄⠄⣠⣴⣿
```
~~~

I can't find a better text picture right now. Maybe I'll do it in the morning. Ya get the gist.

**Comment by damionx7** [comment]
Hey. Do you want these images to appear in Gallery section ?

**Comment by rokejulianlockhart** [comment]
@damionx7, yeah. I think it'd be a really unique feature if text images could appear in the Gallery, since IMO they're pretty much images as much as other formats are.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/10#issue-1673993050

@damionx7, transferred to https://zettel-notes.canny.io/feature-requests/p/add-text-images-to-images-section-if-surrounded-by-fenced-code-block-with-correc per https://github.com/damionx7/Zettel-Notes-Documentation/issues/48#issuecomment-2057164751.

**Comment by RokeJulianLockhart** [comment]
https://github.com/damionx7/Zettel-Notes-Documentation/discussions/73#discussion-6836180
