### ISSUE TITLE
Git info uneditable in edit repo

### ISSUE THREAD

**Issue by spc789** [damionx7/Zettel-Notes-Documentation#102]
After a repo is created, if one uses the edit repo functionality (most right button next to the repos name) one can't edit the git parameters

**Comment by damionx7** [comment]
Hey. You can edit git settings by clicking edit synchronization in repository settings.

**Comment by spc789** [comment]
Unless I miss something, it seeks that option isnt available

![2024_06_25_17.04.15.jpg](https://github.com/damionx7/Zettel-Notes-Documentation/assets/85083997/fd8dce8a-394e-4466-8d8a-eeba5c9a86ca)

![2024_06_25_17.03.37.jpg](https://github.com/damionx7/Zettel-Notes-Documentation/assets/85083997/81145aea-8ae7-4fd2-b4bd-5d05975cf2c8)

![2024_06_25_17.03.52.jpg](https://github.com/damionx7/Zettel-Notes-Documentation/assets/85083997/20332dd7-ac9b-4250-a7b9-e239b106b7b8)

**Comment by damionx7** [comment]
Git setup can be done only while creating repository. And once you have setup git repository, only then you can edit git settings. 

Please follow this documentation link for more details and video https://znotes.thedoc.eu.org/repository/synchronization/git/.

**Comment by damionx7** [comment]
I am closing this issue as I guess this has been resolved.
