### ISSUE TITLE
Encryption functionality is broken on Andoid 11 (Lineage OS)

### ISSUE THREAD

**Issue by chromer030** [damionx7/Zettel-Notes-Documentation#109]
Android: 11
App version: 2.6

https://github.com/damionx7/Zettel-Notes-Documentation/assets/13361552/4fac2776-d530-4e5d-a22d-951f708cd4df

Password does'nt save on both: End to End & Password

**Comment by damionx7** [comment]
Hey! Can you also tell which device are you using.

**Comment by chromer030** [comment]
> Hey! Can you also tell which device are you using.

Hey buddy!

Asus ZenFone Selfie (ZD551KL)
SoC: Qualcomm Snapdragon 615 (MSM8939)
Ram: 3G
ROM: LineageOS (Android 11)

**Comment by damionx7** [comment]
I can't replicate this issue with any of my devices and emulator running android 11.

**Comment by chromer030** [comment]
I tested functionality on my main device and it's working.
Perhaps oldness of device is the cause.
Currently i close this issue, we can reopen if it persists.

thanks for your testings and efforts.
