### ISSUE TITLE
[Feature Request] Automatic list numbering only works for first level of list depth.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#11]
As previously explained in https://github.com/damionx7/Zettel-Notes-Documentation/issues/9#issue-1673990191:

<blockQuote>

When typing numbered lists, I tend to use

```markdown
0. entry
0. entry
0. entry
```

rather than

```markdown
0. entry
1. entry
2. entry
```

because most Markdown processors automatically number the list, as [Zettel](https://play.google.com/store/apps/details?id=org.eu.thedoc.zettelnotes) does.

</blockQuote>

However, *this only works one level deep* in every Markdown processor that I've tried:

```markdown
0. works.
0. 0. whereas, this plus...
0. 0. ...this shall not work.
```

**Comment by damionx7** [comment]
I guess its a feature, not a bug.

**Comment by rokejulianlockhart** [comment]
I don't really mind what it's called, bur are you sure, @damionx7? That seems like something one would expect to work.

**Comment by damionx7** [comment]
Hey. I only changed it as bugs have top priority in comparison to feature requests.

**Comment by damionx7** [comment]
> I don't really mind what it's called, but are you sure, @damionx7? That seems like something one would expect to work.

Can you quote some applications that implement this ? I would like to explore this feature.

**Comment by rokejulianlockhart** [comment]
I can't provide any examples. I know I've been able to use it twice, so there is a Markdown processor out there that supports it (although it might be non-OSS) but I don't remember where.

0. test
0. 0. test
0. 0. test

Not even GitHub does.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/11#issue-1673996903

@damionx7, transferred to https://zettel-notes.canny.io/feature-requests/p/automatic-list-numbering-only-works-for-first-level-of-list-depth per https://github.com/damionx7/Zettel-Notes-Documentation/issues/48#issuecomment-2057164751.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/11#issuecomment-2057484987

Actually, per https://github.com/markdown-it/markdown-it/issues/939#issuecomment-1817536786, this wouldn't have been possible anyway.
