### ISSUE TITLE
[Feature Request] Checkboxes outside filled list entries don't render.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#12]
```markdown
0. [ ] entry
```
works, whereas
```markdown
0. [ ]
```
does not. However, this is not limited to unfilled lists – checkboxes do not appear to render anywhere outside of syntactically perfect lists. I believe that I should be able to place a checkbox anywhere, and can with most other software.

**Comment by rokejulianlockhart** [comment]
Can you reopen as a feature request, then? Most Markdown processors render the checkboxes outside of lists, so when I view them via Zettel, I'm left with square brackets that should be rendered.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/12#issuecomment-1516322291

@damionx7, transferred to https://github.com/github/cmark-gfm/issues/364#issue-2244301425.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/12#issuecomment-2057510161

Transferred to https://github.com/damionx7/Zettel-Notes-Documentation/discussions/64#discussion-6835421 per https://zettel-notes.canny.io/feature-requests/p/feature-requests-are-being-moved-to-github.
