### ISSUE TITLE
Rendering of markdown lines beneath ---

### ISSUE THREAD

**Issue by spc789** [damionx7/Zettel-Notes-Documentation#120]
It occured to me that lines beneath tripple dashes (---) which render a line in markdown always render a heading text below it. Even if there is no # in front of the next line.

Example 1 : 

Text 
Text 
---
This renders as a heading but shouldn't

Example 2 : 

Text
Text
---
# This renders as a heading and is ok

**Comment by damionx7** [comment]
Hey. This is intentional and according to commonmark specs. Read more at https://spec.commonmark.org/0.30/#setext-heading.
