### ISSUE TITLE
Tag search bug

### ISSUE THREAD

**Issue by gwmatthews** [damionx7/Zettel-Notes-Documentation#127]
First, thanks for a nice app! It's great so far for taking notes and linking and tagging them and synching with other devices through GitHub.

I have come across a bug when filtering by tag. Entering the tag #tag manually automatically filters the shown files as I type. But clicking on a tag as it is listed at the bottom of a note listed on the home screen inevitably opens up the most recently created file, whether or not it has the particular tag. Only when I click the back arrow on the top left of the screen do I get a directory view of the filtered notes.

**To reproduce:**
- create new note with tag #foo
- go to directory and click on any another tag (#bar) at the bottom of any note
- newly created note opens instead of filtered directory listing 
- clicking top left back arrow shows desired filtered view

It's only an extra click that is needed, so this is not an app crushing bug, but an annoyance more than anything.

System details -- Android 12 on a newish Lenovo M10 (3rd gen) tablet.

Thanks!

**Comment by damionx7** [comment]
Hey. Thank you for reporting this bug. I have fixed it. It will be live the next update.
