### ISSUE TITLE
Fleeting Note With Template Launcher Not Fully Respecting Template

### ISSUE THREAD

**Issue by rholloway** [damionx7/Zettel-Notes-Documentation#142]
On android when creating a new "fleeting note with template" launcher icon, the note that is generated includes the template contents but it also includes other stuff. This breaks functionality. For instance, if I put frontmatter at the beginning of my template, when I use this quick note icon it will stick a blank "Untitled" and extra hyphens at the start of the note, breaking frontmatter.

I believe the template should be used exactly as is without appending any additional data into the note body unless specified via placeholders or something. It's a pain to remove the extra content from mobile

**Comment by damionx7** [comment]
Hey. Thanks for reporting this issue,. I have added a new "$default-text$" variable in template. When this variable is present then repository default text will be added to a note file.
