### ISSUE TITLE
Search does not work in markdown tables

### ISSUE THREAD

**Issue by tkuraku** [damionx7/Zettel-Notes-Documentation#144]
Search Does not work in Markdown tables. Maybe tables should be rendered in ASCII so they can still be searched?

**Comment by damionx7** [comment]
Yes. Its a known issue due to underlying markdown rendering library used.

**Comment by tkuraku** [comment]
It might be nice to have the option to view the txt file in read only mode for cases like this.

Thank you!

**Comment by damionx7** [comment]
There is an editor button called Lock / Unlock editing. Please try it.
https://znotes.thedoc.eu.org/note/editor/?h=text+manipulation+buttons#text-manipulation-buttons

**Comment by tkuraku** [comment]
That works great. It would be convenient to have a setting to set it to locked by default.

**Comment by tkuraku** [comment]
Just wanted to bump this. The work around going to the edit view works. But it isn't very convenient compared to the normal view. I understand it is probably a lot of work, but that functionality would be a huge quality of life improvement.
