### ISSUE TITLE
[Feature request] Add multiline spoiler tag, like `</spoiler>`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#15]
I use Bitwarden as my password manager. Unfortunately, it doesn't work offline. Consequently, I must occasionally save sensitive information to a temporary note. I would like for this and other reasons to be able to hide text with something like a `<spoiler>` tag, because many services (Disqus, par example} already support it.

**Comment by damionx7** [comment]
Hey. You can use >!spoiler!<  format for hiding sensitive text.

**Comment by rokejulianlockhart** [comment]
Thanks!

**Comment by rokejulianlockhart** [comment]
This doesn't work multiline.

**Comment by damionx7** [comment]
I have added this feature. 

You can use multiline spoilers using html tag <spoiler>

**Comment by RokeJulianLockhart** [comment]
Thank you!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/15#issuecomment-1763364173

https://github.com/whatwg/html/issues/9926#issue-1990303487 would upstream this, likely into CommonMark. [^1]

[^1]: [`github.com/commonmark/commonmark-spec/blob/02db52e6878dd0997402ca3ba025883f6c7e3e5f/spec.txt#L2360C4-L2360C15`](https://github.com/commonmark/commonmark-spec/blob/02db52e6878dd0997402ca3ba025883f6c7e3e5f/spec.txt#L2360C4-L2360C15:~:text=%23%23-,HTML%20blocks,-An%20%5BHTML%20block%5D(@))
