### ISSUE TITLE
set date

### ISSUE THREAD

**Issue by tangshg** [damionx7/Zettel-Notes-Documentation#150]
I set $yyyy MM dd HH: mm: ss $$in two places, but when I use it in my notes, one place displays: 2024-09-05 16:31:26, and the other directly displays $yyyy MM dd HH: mm: ss $$. How can I make both places display 2024-09-05 16:31:26?
I'm using pictures to express my question. Can you understand? I can't speak English

![Attachment-2024-09-05_6](https://github.com/user-attachments/assets/fe5779e9-e1cb-4547-b639-412c563186a8)
![Attachment-2024-09-05_4](https://github.com/user-attachments/assets/9fc41893-18d4-4f21-a462-000fdcc530ed)
![Attachment-2024-09-05_7](https://github.com/user-attachments/assets/750a81ba-98b6-43cd-8cb8-b3b17d1ff30f)
![Attachment-2024-09-05_5](https://github.com/user-attachments/assets/7b2b119c-dc30-4c2b-ac1b-e2d53df99d44)

**Comment by damionx7** [comment]
Hey! I understand your issue. You should use text snippets if you want to use date format or time as variable. Markdown styles insert button as is with no modification. 
For more information, please check out documentation https://znotes.thedoc.eu.org/note/editor/?h=snippe#text-snippets-button.

**Comment by tangshg** [comment]
I've taken care of it, thank you!
