### ISSUE TITLE
[Bug] Searching in `git` repository reliably crashes Zettel.

### ISSUE THREAD

**Issue by rokejulianlockhart** [damionx7/Zettel-Notes-Documentation#16]
Searching more than 3 characters always crashes Zettel when searching in my custom `git` repository, but not in the Dropbox-synchronized App Folder repository.

https://user-images.githubusercontent.com/42837531/233064340-c9d560e0-fd05-4ccf-91a0-99458b184abf.mp4

Unfortunately, due to https://forum.fairphone.com/t/market-feedback-agent-unusable-since-a12-update/95335, I'm unable to [send logs](https://support.google.com/googleplay/android-developer/answer/9859174?hl=en-GB) without assistance by the developer.

**Comment by rokejulianlockhart** [comment]
Turns-out that synchronization wasn't necessary. Merely searching in the repository is enough to always crash the application.

Unfortunately, due to https://forum.fairphone.com/t/market-feedback-agent-unusable-since-a12-update/95335, I'm unable to send logs without assistance by the developer.

**Comment by damionx7** [comment]
I don't think synchronization would affect the search. 

Can you give me read access to the affected git repository ?

**Comment by rokejulianlockhart** [comment]
Yes, but it's in GitLab rather than GitHub, so you'll need to DM me the relevant credentials at https://t.me/rokejulianlockhart

**Comment by rokejulianlockhart** [comment]
I've sent an e-mail to info@thedoc.eu.org.

**Comment by damionx7** [comment]
It is related to large file size. I will solve this issue.

**Comment by damionx7** [comment]
This issue is resolved in latest release (v2.0.2).
