### ISSUE TITLE
The next click on "Select Line(s)" does not highlight the next line

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#163]
Hi, I may not understand correctly, but ...  

The tool is called "Select Line(s)". "Line (S !!!)".  

I'm waiting that each next press will expand the release to the next line.  

You could realize such behavior!  

Thank you for your attention and the amazing "Zettel Notes"

![Select_Lines_Editor_Toolbar.jpg](https://github.com/user-attachments/assets/2e25c017-5a59-4481-8222-1b3a195d7fb9)

![Select_Lines_1_Click.jpg](https://github.com/user-attachments/assets/e23c484b-762e-461e-b662-98f722cb12c9)

![Select_Lines_2_Click.jpg](https://github.com/user-attachments/assets/a0e2247e-7ce9-4c91-aa84-e959b791f50b)

![Select_Lines_3_Click.jpg](https://github.com/user-attachments/assets/38accbd0-ead6-4de9-a15f-265496cbe0cc)

**Comment by damionx7** [comment]
You are right about the name of this editor button 😄. I will add this feature.

**Comment by damionx7** [comment]
I have fixed this. It will be live in version 2.7.4.

**Comment by irmod** [comment]
Thank you! Great job! Well done!!!

вс, 20 окт. 2024 г., 17:58 Rohit ***@***.***>:
