### ISSUE TITLE
The Recycle bin Settings are not obvious

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#164]
For me, setting up the behavior of the Recycle Bin was not obvious. 

"If you set it as 0, files will not be removed from recycle bin."

Perhaps you can add a small explanation to the Recycle bin Settings page.  

This will make "Zettel Notes" more friendly.

 Thank you

![Recycle_Bin_02.png](https://github.com/user-attachments/assets/9c894833-851b-4ab8-98f9-34fa6431bfdb)

**Comment by damionx7** [comment]
I have improved the summary for this setting.

**Comment by irmod** [comment]
> I have improved the summary for this setting.

Thank you!  In version 2.7.4 you added a clear comment for choosing a setting.  I am inspired by your reaction to suggestions!  Fabulous!!!

**Comment by irmod** [comment]
Thank you!  In version 2.7.4 you added a clear comment for choosing a
setting.  I am inspired by your reaction to suggestions!  Fabulous!!!

вт, 15 окт. 2024 г., 21:24 Rohit ***@***.***>:
