### ISSUE TITLE
There is no vertical scrolling in the list of Templates when I Create a new note

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#168]
Please add the ability to scroll the list of templates in the menu for creating a new note from a template.

To reproduce the error:

- Long press on the "Create new note" button ("+").
- Select the "Append Template" checkbox.
- Open the list of templates.
- The "Gboard" keyboard overlaps the list of templates.
- **There is no vertical scrolling in the list of templates.**  I only have the first 5 templates out of 7 available.

![Create_new_notes_from_Template.png](https://github.com/user-attachments/assets/414a6423-10ca-4f7e-b52d-0ca5e23b1814)

![Templates.png](https://github.com/user-attachments/assets/cc415a49-7c37-4b81-814c-af22a2b14f20)

- Zettel Notes v.2.7.3
- Xiaomi Redmi Note 7 (API 28)
- 64-bit ARMv8-A
- Android 9 (Pie)

**Comment by damionx7** [comment]
I have added this feature. It will live in the next update.

[Screen_recording_20241020_111221.webm](https://github.com/user-attachments/assets/14122ceb-23dc-4c0e-9ef8-fc3a00fa7613)

**Comment by irmod** [comment]
Hi,

Unfortunately, in version 2.7.4, when you select the template drop-down
list, the keyboard remains in the foreground. The keyboard closes the list
of templates. You may note that this may be caused by the active name input
field for the note being created...

вс, 20 окт. 2024 г., 8:43 Rohit ***@***.***>:

**Comment by damionx7** [comment]
> Hi, Unfortunately, in version 2.7.4, when you select the template drop-down list, the keyboard remains in the foreground. The keyboard closes the list of templates. You may note that this may be caused by the active name input field for the note being created... This is a recording from my screen: https://github.com/user-attachments/assets/67dd7bea-d8d6-4ad5-b256-a646fa567149

Thanks for the video. I have now changed the spinner behavior. It will show a dialog above keyboard. This should fix this issue.


![Screenshot_2024-10-27-16-55-06-28_377fe8767025e4fa6dddb62d6df8f716](https://github.com/user-attachments/assets/16bb8b30-7a91-4e6f-aada-45ad361d609e)

**Comment by irmod** [comment]
> > Hi, Unfortunately, in version 2.7.4, when you select the template drop-down list, the keyboard remains in the foreground. The keyboard closes the list of templates. You may note that this may be caused by the active name input field for the note being created... This is a recording from my screen: https://github.com/user-attachments/assets/67dd7bea-d8d6-4ad5-b256-a646fa567149
> 
> Thanks for the video. I have now changed the spinner behavior. It will show a dialog above keyboard. This should fix this issue.
> 
> 
> ![Screenshot_2024-10-27-16-55-06-28_377fe8767025e4fa6dddb62d6df8f716](https://github.com/user-attachments/assets/16bb8b30-7a91-4e6f-aada-45ad361d609e)
> 

Thank you for your attention.  I will definitely inform you about the results when I can test the changes

**Comment by irmod** [comment]
- Zettel Notes v.2.7.5
- Xiaomi Redmi Note 7 (API 28)
- 64-bit ARMv8-A
- Android 9 (Pie)

I have to close the keyboard to access the full list of templates.

https://github.com/user-attachments/assets/a56d0f15-83e4-4481-9184-92af15a8a396

I can assume that my version of the keyboard needs an update.  However, I am completely happy with my keyboard setup.  So I found a solution for me.

https://github.com/user-attachments/assets/3a9336eb-a0bc-4ddc-bc40-65f0c2a8d4cf

Please don't waste your time on one person's problem...

☹️

**Comment by irmod** [comment]
@damionx7, it doesn't seem to depend on the keyboard

![Hacker_Keyboard.png](https://github.com/user-attachments/assets/d25f68b7-c676-44f1-8e96-d890798a1044)

![Smart_Keyboard.png](https://github.com/user-attachments/assets/aa76d524-8a37-4cfe-a319-caa5ad892c13)

**Comment by damionx7** [comment]
Interesting. I can't replicate the issue with these keyboards. Can you try this on a different device.

**Comment by irmod** [comment]
Unfortunately, this is the only device I have on hand...

- Xiaomi Redmi Note 7 (API 28)
- 64-bit ARMv8-A
- Android 9 (Pie)

☹️

**Comment by irmod** [comment]
@damionx7 
I can only assume that the problem is related to the application's development environment... Other applications on my device have forms with text and drop-down selection lists, but when I go to the list, the keyboard disappears from the screen.

**Comment by irmod** [comment]
@damionx7 

I found a solution for my device.  I close the keyboard BEFORE accessing the selection from the drop down list.

Thank you for the time you devoted to my problem...

**Comment by damionx7** [comment]
I will fix this issue in upcoming updates by closing the keyboard before opening template dialog. This should fix it.

**Comment by irmod** [comment]
Wow!!!  @damionx7 – You are a real Jedi!

**Comment by irmod** [comment]
@damionx7, your fixes are working correctly.  

Perhaps you can take the time to adjust the position, size and color of the drop-down lists

![Dropdown_Size_1.jpg](https://github.com/user-attachments/assets/4fbb2416-4f53-4a0d-984f-769383afb49c)

![Dropdown_Size_2.jpg](https://github.com/user-attachments/assets/2efc761f-a491-4b7f-9211-c5f38304b803)

![Dropdown_Size_3.jpg](https://github.com/user-attachments/assets/613b3468-af3d-4f1a-97af-5582590d6e84)
