### ISSUE TITLE
[Feature Request] Headerless Markdown tables.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#17]
This is merely a matter of support for whichever Markdown processor Zettel uses, per https://stackoverflow.com/a/17543474/9731176.

This would permit

```markdown
| ---- | ---- |
| data | data |
```

(headerless)

in addition to the standard

```markdown
| head | head |
| ---- | ---- |
| data | data |
```

**Comment by damionx7** [comment]
Markdown library that Zettel Notes uses does not have this feature and is not actively maintained.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/17#issuecomment-1877520295

@damionx7, which library does it utilize?

**Comment by damionx7** [comment]
Its Markwon library.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/17#issuecomment-1878067898

@damionx7, https://github.com/noties/Markwon?

**Comment by damionx7** [comment]
> > [#17 (comment)](https://github.com/damionx7/Zettel-Notes-Documentation/issues/17#issuecomment-1878067898)
> 
> @damionx7, https://github.com/noties/Markwon?

Yes. Its https://github.com/noties/Markwon.
