### ISSUE TITLE
Touching the TOC item should bring the focus to the beginning of the heading

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#173]
Tapping Table of Contents (TOC) in "View Mode" moves focus to the last row of the selected header.

Noticeable on long headings of 2-3 lines.

 **I expect to see the entire title.**

Could you change the existing behavior

Best regards for your time

My expectation:

![New_behaviour.png](https://github.com/user-attachments/assets/ab8684d5-1b8b-41b4-af16-b8b2bcc1ca49)

Existing behavior:

![Current_behaviour.png](https://github.com/user-attachments/assets/2dcb6e39-2615-45d7-81e4-8a58c6d0d859)

**Comment by irmod** [comment]
@damionx7

I have added two videos that explain the issue:

- Issue on Zettel Notes v.2.7.4

https://github.com/user-attachments/assets/dbf596a0-42a5-4ef7-867b-ad5cbe349d46

- Correct behavior on another application

https://github.com/user-attachments/assets/3f95399b-eeda-47bd-93f8-c597b224dd88

**Comment by damionx7** [comment]
I have fixed this issue. It will be live in the next update.

**Comment by irmod** [comment]
@damionx7, In version 2.7.6, the transition occurs to the first header line. Great!!!
