### ISSUE TITLE
Show filename instead of title without the extension

### ISSUE THREAD

**Issue by blacklightpy** [damionx7/Zettel-Notes-Documentation#177]
Show filename instead of title shows the filename with .md extension.

If I don't check it, any files having a heading inside will take it as its title, even if the heading is in some code block.

Please fix.

**Comment by blacklightpy** [comment]
moving to right repo

**Comment by blacklightpy** [comment]
Oh, I just realized this app is not free code software..

**Comment by damionx7** [comment]
Hey! You will have to change Prefer Title From option in repository settings. Read more https://znotes.thedoc.eu.org/repository/?h=prefer+tit#6-prefer-title-from

**Comment by damionx7** [comment]
> It does not fix it, unless I use YAML headers. I want the filename without the extension to be used as the title.

Please select `Filename` as option for Prefer Title From field in repository settings and change the note or rescan the repository.

**Comment by blacklightpy** [comment]
Worked. I had Filename instead of Title checked, which I forgot to turn off.
