### ISSUE TITLE
TransportException when setting up git with ssh

### ISSUE THREAD

**Issue by akumar-xyz** [damionx7/Zettel-Notes-Documentation#178]
Please let me know in case I'm missing something here

I'm trying to set up a Git synced repository with the following 

**Repository Url**:
```
ssh://<git-server>:<path-to-repo>
```
I also tried

```
ssh://<git-server>/<path-to-repo>
```

**Username**
```
git
```

**Authentication**

Key Authentication using key manager.

### What I have tested

When I ssh into my server (using my desktop) using the private key created by zettle notes, I'm able to login just fine so I'm pretty confident that its not a problem with my setup.

```sh
# works
ssh -i id_ed25519 git@<git-server>

# works
git clone git@<path-to-repo>
```

## Error Message

Its only showing on toast so this is all I can see

```
org.eclipse.jgit.api.errors: TransportException: ssh://<server-url>/<path-to-repo>: Auth failed for methods 'publickey'
```

On the server end I can see this in the log
```
error: Received disconnect from <ip-address> port 3682:3: com.jcraft.jsch.JSchException: Auth fail for methods 'publickey' [preauth]
```
Is the URL scheme I'm using correct?

**Comment by akumar-xyz** [comment]
![image](https://github.com/user-attachments/assets/d76052ec-8c99-485a-8fcd-299cff2dafbb)

Also, just received this notificatoin

**Comment by damionx7** [comment]
You should try this format `git@github.com:damionx7/Zettel-Notes-Documentation.git`

**Comment by akumar-xyz** [comment]
Yep. That works.
Shall I raise an MR clarifying this in the documentation?

**Comment by akumar-xyz** [comment]
Yep. That works.
Shall I raise an MR clarifying this in the documentation?

**Comment by damionx7** [comment]
> Yep. That works.
> Shall I raise an MR clarifying this in the documentation?

Great. Feel free to contribute.
