### ISSUE TITLE
[Feature Request] Use bookmark tag per-file rather than in database.

### ISSUE THREAD

**Issue by rokejulianlockhart** [damionx7/Zettel-Notes-Documentation#18]
I reorganize my files frequently. This means that documents are moved out of directories and into others. Because the internal bookmark database does not account for this, and fundamentally cannot in a synchronized repository, my bookmarks are removed.

Consequently, [I suggest that the bookmark be stored in the YAML preamble.](https://t.me/c/1571773822/4976) In lieu of this, [I believe that a #bookmark tag should be used.](https://t.me/c/1571773822/4987) I also believe that the bookmark GUI button should remain. However, [this might be difficult if the 2nd implementation is chosen](https://t.me/c/1571773822/4995).

**Comment by damionx7** [comment]
I have added this feature. It will be live in v1.0.91. 

To set bookmark use yaml property 
`bookmark: true` or `bookmark: 1`

To remove bookmark
`bookmark: false` or `bookmark: 0`

Other yaml alias supported are `pin` and `star`
