### ISSUE TITLE
[Feature Request] Use system datetime format, not UNIX Epoch integer, in VCS manager commits.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#19]
When inspecting a commit in the VCS manager, the user is provided a UNIX Epoch timestamp instead of the date formatted per their system preferences.

![Screenshot_20230420-113410](https://user-images.githubusercontent.com/42837531/233341444-f4328b95-9df6-4c1f-a7d5-ae08bde63a8d.png)

> Commit from Zettel Notes at {UNIX timestamp}

This is problematic because no user can easily convert such a large integer into a useful timestamp mentally.

**Comment by damionx7** [comment]
There is option in git setting to modify `commit message`. Read more in documentation https://znotes.thedoc.eu.org/repository/synchronization/git.
