### ISSUE TITLE
The INSERT button is not visible in Table on the Editor Toolbar

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#192]
I don't see the INSERT button in Table on the Editor Toolbar

In Edit Mode I want to insert a Table from the Editor Toolbar. I don't see the INSERT button. When I try to move the Table field up, the table parameters (Rows, Columns) change to the wrong ones...

As a suggestion, you could make a free space big enough for your finger on the right (left) or in the center... But the idea of ​​moving something that moves bothers me...

Could you find a solution

https://github.com/user-attachments/assets/8e5b7161-b7ed-411e-969e-0d512bc91571

**Comment by damionx7** [comment]
Thanks for reporting. I have fixed this issue.

![image](https://github.com/user-attachments/assets/1776a17c-069a-4aba-adc2-9842f6cb05fd)
