### ISSUE TITLE
Replace purple with Accent Color

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#194]
I like purple in themes and interface.  However, you might agree that the Accent Color is more expected

![Purple_to_Accent_Color_01.png](https://github.com/user-attachments/assets/b6b17209-d62c-4e8d-9435-fef6e2104f21)

![Purple_to_Accent_Color_02.png](https://github.com/user-attachments/assets/23aea79f-7c43-412f-afca-539e3ddc131b)

![Purple_to_Accent_Color_03.png](https://github.com/user-attachments/assets/e06b6a19-b198-4bdd-a457-4ffb95b703ff)

![Purple_to_Accent_Color_04.png](https://github.com/user-attachments/assets/9b384399-12af-4b9d-888e-724ba941d0f7)

![Purple_to_Accent_Color_05.png](https://github.com/user-attachments/assets/b20c9f50-28f3-47e0-80f5-0c6d8702576e)

![Purple_to_Accent_Color_06.png](https://github.com/user-attachments/assets/7d496cb5-035b-4185-af7b-12480543f19f)

![Purple_to_Accent_Color_07.png](https://github.com/user-attachments/assets/8d9b5017-575c-4b87-ad3c-8649db810e5e)

**Comment by damionx7** [comment]
Thanks for the images. I have fixed this issue.

**Comment by irmod** [comment]
Well done!  You are the best!
