### ISSUE TITLE
The keyboard overlaps the dropdown list when adding an Attribute

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#196]
It bothers me that the application on mine, and therefore on other devices, can behave unpredictably.  I got the same result by adding Attributes. 

https://github.com/user-attachments/assets/9014bf53-e863-4577-b330-94ae70d93f71

When I go to the text input field, the keyboard is activated and overlaps the drop-down list.  I was able to find a workaround to access the list.  To do this, I close the keyboard before navigating to the dropdown.

For a user who uses Zettel Notes to solve their problems, this will be an obstacle.  If on some configurations the keyboard moves to the background behind the opening list, then there may be configurations where this behavior will be different.

@damionx7 , could you think about how difficult it would be to write a function that will check whether the keyboard is open when the user clicks on the drop-down list.  If the keyboard is open, the function closes the keyboard and opens the list.  Activation of the keyboard in text input fields occurs normally.

I want to believe that you can do this.

**Comment by damionx7** [comment]
Sure. I have added function to close keyboard when user opens the attribute and template list.

**Comment by irmod** [comment]
@damionx7, in version 2.7.6, your magic works!
