### ISSUE TITLE
In a quote, the highlighting of the mark tag is different from the highlighting in the body text

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#198]
Inside a quote in "View Mode" the text color in the  `<mark>text</mark>`  tags is displayed differently.  Compare with tag highlighting in body text.

To check, select Theme "Night" and Markdown Style "Electric Blue Dark", "Oceanic Teal Dark".

![Oceanic_Teal_Dark.png](https://github.com/user-attachments/assets/347f41a6-3ed1-4bcf-b02c-e76d93834e89)

Markdown style text highlighting  `==text==`  appears the same within a quote and in body text.

The general rule is to highlight tags (inline code, strong, em, a, kbd, etc.) in the same style, regardless of their nesting in other blocks.

In "Edit Mode" there is no highlighting for the  `<mark>text</mark>`  tag.  There is a highlight to highlight  `==text==` .

![mark_View_Mode.png](https://github.com/user-attachments/assets/377282b1-58d2-4dc3-860f-fffa7b92f70f)

![mark_Edit_Mode.png](https://github.com/user-attachments/assets/caf9f35f-3fdd-4fa8-8e91-e7c8023e11a0)

@damionx7, I expect that the highlighting will be the same in both "View Mode" and "Edit Mode", regardless of which style blocks it is made within

**Comment by damionx7** [comment]
Thanks for reporting. I have fixed this issue.

**Comment by irmod** [comment]
@damionx7, thank you!  You are the best!!!
