### ISSUE TITLE
Unexpected text appears in Fenced Code View Mode

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#200]
1. I create a Fenced Code block in a note

````
```
```
````

2. Inside the code block I insert a link to the image through the Select File from Gallery menu in the Editor Toolbar.  The image is in the same folder as the note

````
```
![workplace](workplace.jpg)
```
````

![Garbage_in_Fenced_Code_Edit_Mode.png](https://github.com/user-attachments/assets/c1a262a4-b32d-41df-a379-b5b13a4cf809)

3. When I go to View Mode, I see unexpected text in the Fenced Code block

````
![workplace](content://com.android.externalstorage.documents/tree/primary%3Adocuments%2F_Silicon_Valley%2FSoft%2FZettel_Notes%2Frepository/document/primary%3Adocuments%2F_Silicon_Valley%2FSoft%2FZettel_Notes%2Frepository%2F20%20Zettel%20Notes%2Fissues%2F200%2Fworkplace.jpg)
````

![Garbage_in_Fenced_Code_View_Mode.png](https://github.com/user-attachments/assets/ea69afa7-219e-49f4-b73c-51ae46c063be)

When I add any character before `.jpg` inside Fenced Code in Edit Mode, then unexpected text appears in View Mode.

My expectation inside Fenced Code is pure text only

**Comment by damionx7** [comment]
I have fixed this issue. It will be live in the next update.
