### ISSUE TITLE
Inside Markdown formatting Code in View Mode ">!"  appears unexpectedly

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#201]
In Inline Code and Fenced Code in View Mode, the character sequence `>!` is displayed differently than I expect.

![Unexpectedly_Symbol_Edit_Mode.png](https://github.com/user-attachments/assets/ac2e5df6-29e9-4277-9ff0-1fc1198fb5a0)

![Unexpectedly_Symbol_View_Mode.png](https://github.com/user-attachments/assets/dc7e3160-94aa-4a7e-93ad-216969bdfec5)

**Comment by damionx7** [comment]
Thanks for reporting. I have fixed this. It was due to spoiler tag replacing the >! with html entities.
