### ISSUE TITLE
Setting the font for Blockquote

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#203]
@damionx7, could we see in the new version of Zettel Notes setting a custom font for Blockquote in Theme --> Markdown Style --> Edit Theme

https://github.com/damionx7/Zettel-Notes-Documentation/discussions/166

**Comment by damionx7** [comment]
Hey, I have added this feature. I will ship the update in a few days.

**Comment by irmod** [comment]
💕💕💕

**Comment by irmod** [comment]
@damionx7, in version 2.7.6 I can choose my favorite font for quotes!!!  You are a real wizard!!!  Thank you!!!
