### ISSUE TITLE
Links are displayed differently in Markdown Code

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#205]
Zettel Notes v2.7.6

The display of links in Fenced Code and Inline Code in View Mode is different from Edit Mode.

For example:

````
```text
[[Filename]]
[[Filename.md]]
[[Filename|Title]]
[[Filename.md|Title]]
[[Date]]
[[Date]] Title
[Title](Filename)
[Title](Filename.md)
[[../Filename.md]]
```

Inline Code `[[Filename]], [[Filename.md]], [[Filename|Title]], [[Filename.md|Title]], [[Date]], [[Date]] Title, [Title](Filename), [Title](Filename.md), [[../Filename.md]]` out of the Inline Code.
````

![Links_within_Code_01.png](https://github.com/user-attachments/assets/4919adfa-1199-4584-9cf6-8ed9bb0a8835)

![Links_within_Code_02.png](https://github.com/user-attachments/assets/ff41d337-ff0d-4bc7-95ac-2a31ba1fc8f7)

**Comment by damionx7** [comment]
Thanks for reporting. I have fixed this issue.
