### ISSUE TITLE
The snippet removes the previous character

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#213]
Zettel Notes v2.7.7

Inserting a snippet through the `::` context menu removes any significant character (except space and the beginning of a line) in the position preceding the insertion point.

Before inserting a snippet:

````
```
[Zettel Notes](https://znotes.thedoc.eu.org/changelog/)
```
````

After inserting the snippet:

![Snippet_markdown.jpg](https://github.com/user-attachments/assets/22f55113-7d8e-4152-8b51-ee925d00a6ba)

````
``markdown
[Zettel Notes](https://znotes.thedoc.eu.org/changelog/)
```
````

In unpredictable cases (for example, Zettel Notes was restarted), the snippet can be inserted without deleting the previous character. A repeated attempt to insert a snippet occurs with the removal of the previous character.

I expect that inserting a snippet will not change the existing text.

https://github.com/user-attachments/assets/77893116-6dd7-4ee4-b07b-a2c242c599b5

https://github.com/user-attachments/assets/a51178c2-d318-4641-992d-469a74af4a9e

**Comment by damionx7** [comment]
Thanks for reporting. I have fixed this issue.
