### ISSUE TITLE
The Large Headings setting does not change the size of the headers

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#214]
Zettel Notes v2.7.7

@damionx7, 
For pre-installed themes in Zettel Notes (Settings --> Theme --> Markdown Style), the **Large Headings** setting does not change the size of headings displayed in Edit Mode.

![Large_Headings_ZN_Theme.jpg](https://github.com/user-attachments/assets/04832311-508f-4303-a9fe-5c2a2d1efbe0)

![The_Large_Headings_setting_does_not_change_the_size_of_the_headers.png](https://github.com/user-attachments/assets/1a049558-7de7-4980-8c0e-1646c263f82f)

Maybe I misunderstood something or configured something...

After enabling **Large Headings** in Edit Mode, there is no syntax highlighting.

The video turned out to be 11 MB.  That's a lot for GitHub.  I can send the video to your email.

**Comment by damionx7** [comment]
Yes. Please share the video.

**Comment by irmod** [comment]
@damionx7, I sent this video to your email

**Comment by damionx7** [comment]
Can you share this note file also ?

**Comment by irmod** [comment]
Zettel Notes v2.7.8

@damionx7, heading sizes in Edit Mode are proportional!!!  You did it!!!

I sent you an archive with a folder by mail.  The folder contains an extremely large file with a note and four image files for testing.  It may be convenient for us to make corrections in Zettel Notes by checking them on this file.  We can refer to a specific line in a file.

**Comment by damionx7** [comment]
I just tried the files that you sent. The heading sizes render as expected. 

![Screenshot_2024-11-18-15-01-59-28_377fe8767025e4fa6dddb62d6df8f716](https://github.com/user-attachments/assets/1f6562c0-99ff-4048-8cee-a66736cd17c3)

**Comment by irmod** [comment]
@damionx7, as of Zettel Notes v2.7.8, header sizes are displayed correctly. Well done!!!

I sent you the file solely to create a test folder with a note in your repository. I might refer to this note when testing Zettel Notes.

For example, you can now see in View Mode that after links to an image on the Internet in HTML format, there is no space between the image and the Fenced Code, text, or any Markdown block.  The image and Fenced Code are “glued together”...

**Comment by damionx7** [comment]
Thanks. Can you create a new issue for this, so that we can track this more easily. Closing Large Headings issue for now.

**Comment by irmod** [comment]
@damionx7, thanks for the great job!  Large headlines - large success! 💕
