### ISSUE TITLE
The weight of Large Headings is incorrect

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#215]
Zettel Notes v2.7.7

@damionx7, thanks for the ability to display Large Headings in Edit Mode!  Now I can edit a note without switching between Edit Mode and View Mode. This is very convenient and saves my time. It became much easier for me to navigate the note itself. I'm enjoying it!

But could you sort out the increase in the weight of the title font when switching to Edit Mode.

When I first open a note to edit, the headings are the correct size and letter thickness.  But after a second the thickness of the letters doubles... The headings become thick...

![Weight_of_large_headings.jpg](https://github.com/user-attachments/assets/75467e20-7dd5-4535-a7ec-36ae98b6c15f)

This question is about the enlarged headings in my theme, in which I have set my font in Settings -> Theme -> Markdown Style.

In my theme, I use the Roboto Condensed font from Google Fonts for the headings.

https://github.com/user-attachments/assets/87cab7d7-ecb6-45ee-890a-1ddbb10b0c00

**Comment by damionx7** [comment]
I have fixed this issue (v2.7.8)
