### ISSUE TITLE
The Markdown link to the image is displayed strangely inside Fenced Code

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#216]
Zettel Notes v2.7.7

Inside Fenced Code, spaces in the link are replaced with `%20`.

I expect there will be no internal changes to Fenced Code.

**Edit Mode:**

```markdown
![workplace new](/20 Zettel Notes/tests/workplace new.jpg)
```

```markdown
![workplace new](workplace new.jpg)
```

**View Mode:**

```
![workplace new](/20%20Zettel%20Notes/tests/workplace%20new.jpg)
```

```
![workplace new](workplace%20new.jpg)
```

**Comment by damionx7** [comment]
I have fixed this issue. (v2.7.8)

**Comment by irmod** [comment]
Zettel Notes v2.7.8

@damionx7, I checked.  My image links are now displayed correctly in Fenced Code

Thanks for the quick response
