### ISSUE TITLE
Backup Keyboard Shortcuts menu is missing

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#218]
Zettel Notes v2.7.8

@damionx7, have you decided to give up Backup Keyboard Shortcuts? ☹️

![IMG_20241117_010753.jpg](https://github.com/user-attachments/assets/b17da928-31f7-4edb-bd2b-6dc20098f8e2)

**Comment by damionx7** [comment]
I will add this feature. It was not working previously.

**Comment by damionx7** [comment]
Btw, which hardware keyboard do you use ?

**Comment by damionx7** [comment]
I have added this feature. It will be live in the next update.

**Comment by irmod** [comment]
@damionx7, I'm looking forward to the Zettel Notes update!
