### ISSUE TITLE
Everytime I enter a colon, a search box pops up, and I want to turn that off

### ISSUE THREAD

**Issue by nonplayer** [damionx7/Zettel-Notes-Documentation#220]
This is a maddening feature that I can't find a way to turn off. Every time I enter a colon character (or Shift+Semicolon) on my bluetooth keyboard, a search window pops up and there's no way to exit it from the keyboard. I'm trying to work with some table formatting, and this makes it impossible to manually enter alignment codes using standard Markdown formatting.

I've looked through every settings screen, and nothing indicates this function is configurable. Please let us turn this off. No single keyboard character should take the user out of the active editor like this.

Thank you!

**Comment by damionx7** [comment]
Hey, There was a new feature to open text snippets when user pressed `::`. https://znotes.thedoc.eu.org/changelog/?h=for+inserting+Text+Snippets#277.

I have tried it with my bluetooth keyboard and the text snippets search dialog pops up only after pressing colon two times. If possible, can you share a video of this issue. Thanks

**Comment by nonplayer** [comment]
I don't have a way of recording a video unfortunately.

If I enter a free-standing colon, the search pops up. If I try to enter a colon on a table - such as "--:" -  to set it to center or right-align, the same thing happens. If I enter a colon as the first character on a new line, again the search pops up.

It's really bad, to the point that I've had to go back to using a different editor. Please let us turn these things off when they are introduced, some users have valid needs to enter one or more characters freely and having them launch unwanted menus without warning is interruptive to a writing flow. If I could, I would turn off all of them, I don't want any dialogs popping up outside of specific CTRL-key commands.

Thanks again.

**Comment by damionx7** [comment]
Sure, I will add settings option to disable this feature.

**Comment by nonplayer** [comment]
Fantastic, thank you!

**Comment by damionx7** [comment]
I have added settings option to disable editor text shortcuts. It will be live in the next update.
