### ISSUE TITLE
Google Drive sync error

### ISSUE THREAD

**Issue by thdoan** [damionx7/Zettel-Notes-Documentation#223]
I can't reproduce the error anymore after deleting and recreating my Google Drive folder, but earlier I kept getting this error when syncing with a large folder (over 200 MD files) on Google Drive:

![image](https://github.com/user-attachments/assets/3452a2c7-c44e-4f94-9cca-bd6ef51cfbcf)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String I3.b.h()' on a null object reference
```

**Comment by damionx7** [comment]
Google drive sync will be removed in upcoming versions. You can read more about the reason here https://t.me/zettelnotes/345.
