### ISSUE TITLE
[Bug] Bibtex not working

### ISSUE THREAD

**Issue by bambirombi** [damionx7/Zettel-Notes-Documentation#23]
I have installed both BibTex Manager and Zettel Notes. In Zettel Notes I added the .bib file but I am unable to get it working.
When opening Zettel Notes > BibTex I get this error:
![bibtex-error-zettel-notes](https://user-images.githubusercontent.com/87095035/236167624-99e31afb-f940-4938-9121-26a1c5c4daf3.png)

**Comment by damionx7** [comment]
Hey. Its due to corrupted bibtex file.

**Comment by damionx7** [comment]
I have published v1.0.4 on play store. This issue is fixed in that version.

**Comment by bambirombi** [comment]
@damionx7 Have you made the updates in F-droid? I have updated Bibtex Manager and it is working, but Zettel Notes has not have any update and it continues to have the error, so I cannot add any citation.
