### ISSUE TITLE
[FR] Add support for wikilinks to headings

### ISSUE THREAD

**Issue by bambirombi** [damionx7/Zettel-Notes-Documentation#24]
Like in obsidian or [marksman](https://github.com/artempyanykh/marksman).

The syntax:

[[filename#headingname]]

It would also be interesting to update the wikilinks to filenames and headings when those are changed.

**Comment by rokejulianlockhart** [comment]
More specifically, what does this actually do?

**Comment by damionx7** [comment]
I have added this feature. It is live in v 2.2.7 https://znotes.thedoc.eu.org/changelog/#227
