### ISSUE TITLE
Not opening files (Permission Denied)

### ISSUE THREAD

**Issue by guihasparyk** [damionx7/Zettel-Notes-Documentation#25]
I can't open markdown files from file manager. It says permission denied and the app doesn't require files acess permission, how is that possible?

**Comment by damionx7** [comment]
can you share video ? also what is your android version and model.

**Comment by guihasparyk** [comment]
![Screenshot_20230511_130753_com.google.android.packageinstaller.jpg](https://github.com/damionx7/Zettel-Notes-Documentation/assets/50344202/ef7578a7-353d-4c65-9940-990f3352b500)

https://github.com/damionx7/Zettel-Notes-Documentation/assets/50344202/dd40c6cd-4c00-44df-80ac-4458c9019dcf

![Screenshot_20230511_131117.jpg](https://github.com/damionx7/Zettel-Notes-Documentation/assets/50344202/228a9f4d-4e8a-4b45-8922-764b5079d0d7)

**Comment by damionx7** [comment]
Can you try changing file explorer ?

**Comment by guihasparyk** [comment]
I managed to open with the core file explorer from huawei, but my intention was to open files from the home screen using a widget of File Widget app... Wich also says permission denied like X-plore do.

Is it possible?

**Comment by damionx7** [comment]
You can also share notes from zettel notes to create launcher shortcuts for both media files and notes.

**Comment by guihasparyk** [comment]
I have a vault full of notes and I need quick acess trough home screen, and they always being edit, exported or deleted. It's a hassle for me creating launch icons for every new note,or deleting them.

I would like to make a feature request:
- A widget to view and acess files and folders from the home screen.

**Comment by damionx7** [comment]
See this telegram message on how to resolve this. Basically its related to content uris.
https://t.me/c/1571773822/5163

**Comment by damionx7** [comment]
> I have a vault full of notes and I need quick acess trough home screen, and they always being edit, exported or deleted. It's a hassle for me creating launch icons for every new note,or deleting them.
> 
> I would like to make a feature request:
> 
>     * A widget to view and acess files and folders from the home screen.

I have added note widgets. They will be live in the next update.

**Comment by guihasparyk** [comment]
That's awesome. I'll test it out and share with my friends.
