### ISSUE TITLE
[Bug] Bibtex/citations do not work

### ISSUE THREAD

**Issue by bambirombi** [damionx7/Zettel-Notes-Documentation#28]
Th error I mention in #23 now is not happening but the citations do not make any sense...

The citation format should be the one you have set in Zotero in Better Bibtext > Preferences > Citation Keys > Citation key formula.

When I try inserting a citation in Zettl Notes it gives me something like this:

`{cite:550}`  instead of @author2020

**Comment by damionx7** [comment]
Hey. Check out this video to see how to use citations https://t.me/zettelnotes/114. Citations are used to generate bibliography.

**Comment by bambirombi** [comment]
@damionx7 Ok. Now I see how it works. 

Although there are 2 problems:

1. It creates `# Bibliography` every time I render de citation, so I end up with multiple `# Bibliography` sections instead of only one.
2. I still think using the @citekey is the best options because it works in obsidian, logseq, zettlr... and because is the format you need to use when exporting to .docx, .pdf, .html... when using pandoc. Using a different syntax makes compatibility impossible in respect to citations. Moreover, for example, zettlr already renders as "normal" the citekyes (for example, @Uri2000 is rendered as Uri (2000) and [@Uri2000] as (Uri, 2000) having into account the CSL you add.

**Comment by damionx7** [comment]
1. I have fixed bibliography duplication.
2. Added @{citekey}.

Thanks for reporting this bug. It will be live in the next update.

**Comment by bambirombi** [comment]
@damionx7 Could you give the option to make @citekey instead of @{citekey}?

**Comment by damionx7** [comment]
Can you give some examples as to why @citekey would be better. As @{citekey} is supported with pandoc if thats what you are using.
