### ISSUE TITLE
Change Default Folder Location for New Notes

### ISSUE THREAD

**Issue by AaronKnowls** [damionx7/Zettel-Notes-Documentation#30]
When creating a new note from the app shortcut, you're able to decide the repository where it will be created (before hand, in the options), but not the particular folder.

I haven't found a way to modify that, and tell it the exact folder in the repository where to save them by default.

Is there a way to do that? It will be useful and remove the need to having to move them later.

Thank you for this amazing software and for its continuous development. Thank you thank you!!

**Comment by damionx7** [comment]
Hey Aaron, I am really glad that you like Zettel Notes.

When you click on 'Add Note' Launcher shortcut, then a dialog is shown to add note. When you click on it, you are provided with option to select repository and subfolder. Maybe I don't understand your issue but can you please share screenshots or maybe a video describing this issue.

**Comment by damionx7** [comment]
Sure. I will add this feature in upcoming versions.
