### ISSUE TITLE
[Feature Request] Object retrieval should be asynchronous.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#31]
> ![Screenshot_20230831-005340.png](https://github.com/damionx7/Zettel-Notes-Documentation/assets/42837531/1ac90631-bee3-4855-81a0-ec7c6a0da875)

I shouldn't need to wait at that screen for it to retrieve objects – that dialog should show as a notification.

**Comment by damionx7** [comment]
Repository initialisation is necessary. Until repository is set up user can't do anything (eg. create notes, delete some notes). This will mess up the git head.

**Comment by rokejulianlockhart** [comment]
Yeah, I understand that. I don't mean that I should be able to use the repository before it's properly initialized, only that I should be free to use the rest of the application (or at least leave the app in the background and have the progress continue in a notification) whilst it's initializing. Does that make sense?

**Comment by damionx7** [comment]
Yes. I will come with something. Thanks for reporting.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/31#issue-1874535608

@damionx7, transferred to https://zettel-notes.canny.io/feature-requests/p/object-retrieval-should-be-asynchronous per https://github.com/damionx7/Zettel-Notes-Documentation/issues/48#issuecomment-2057164751.

**Comment by RokeJulianLockhart** [comment]
https://github.com/damionx7/Zettel-Notes-Documentation/discussions/71#discussion-6836178
