### ISSUE TITLE
How do I unpin notes from the notification area?

### ISSUE THREAD

**Issue by guihasparyk** [damionx7/Zettel-Notes-Documentation#32]
I've recently shared a note with the function to it to my notification area, but now I want to remove it.
How am I supposed to do that? I've searched everywhere in the app, am I missing something?

**Comment by damionx7** [comment]
Currently you will have to force close zettel notes app to remove notification. I will add feature to manage notifications in upcoming versions.

**Comment by guihasparyk** [comment]
Thanks for response.

Congrats for the hard good work. 🎉
