### ISSUE TITLE
[Feature Request] Notes preview on notes list

### ISSUE THREAD

**Issue by Request-timed-out** [damionx7/Zettel-Notes-Documentation#39]
As my notes grow, it has become harder for me to find a specific note taken before only by searching for their names and tags (for moods and minds, sometimes very hard to pick a name and tags for them too), so is it possible for Zettel Notes to priview my notes on `Notes List` like [Quillpad](https://github.com/quillpad/quillpad) does, that would be very nice.

**Comment by damionx7** [comment]
Sure. I will add this feature.

**Comment by damionx7** [comment]
Hey! This feature is live in the latest versions. https://znotes.thedoc.eu.org/changelog/?h=cha#251.
