### ISSUE TITLE
There should be a choice between password auth and private key auth

### ISSUE THREAD

**Issue by wrvsrx** [damionx7/Zettel-Notes-Documentation#4]
Users can use password/token auth or private key auth. However, in the settings of this app we have to set both password auth and private key auth to make sync works (#2 also mentions that).

There should be a "xor" relation between these two options instead of "and".

**Comment by damionx7** [comment]
I have fixed this in version 1.0.75.

**Comment by rokejulianlockhart** [comment]
![Screenshot_20230419-123714](https://user-images.githubusercontent.com/42837531/233063241-50b7a52d-5e99-4325-a8c8-40340857a100.png)

I don't see any kind of exclusive relationship between them. Does anything there demonstrate that only one option can be used?

**Comment by damionx7** [comment]
I have fixed this in the latest version.
