### ISSUE TITLE
cannot decrypt after upgrading app!

### ISSUE THREAD

**Issue by cipitaua** [damionx7/Zettel-Notes-Documentation#41]
I have a series of notes with extension .md.aes  which after upgrade are no longer recognized as encrypted and are opened as plain text files, resulting unusable.

How can I recover the encrypted content?

I do have backups. Thank you.

**Comment by damionx7** [comment]
hey. please remove and add repository again. the mechanism to detect encrypted files was changed in latest update. adding repository again will rescan your encrypted notes.

**Comment by damionx7** [comment]
and when you add repository again, use same encryption method and password as before.

**Comment by cipitaua** [comment]
it says "can't decrypt" :(

**Comment by cipitaua** [comment]
is there a command line way, i.e. using pgp ?

**Comment by damionx7** [comment]
gpg cant be used for these password encrypted notes. 
Can you please ensure following:
1) You didn't reset Zettel Notes (which would have cleared salt hash)
2) You are using the same password which was used for encryption
3) You have set the same older password encryption method not the latest end to end encryption.

**Comment by cipitaua** [comment]
I reply point-by-point:
1. The only thing I did is to update through f-droid. No idea why the salt should have changed.
2. If one enters the wrong password it says "incorrect password", otherwise it says "can't decrypt".
3. I always use the simple "password" method.

Question: is it possible to decrypt from command line using gpg? I'm on linux environment. Thank you for support.

**Comment by damionx7** [comment]
it is possible but you will have to code it yourself as there are no ready made scripts to decrypt these encrypted note files. if you want to proceed, send me an email.

can you try after restoring from one of the backup files and then selecting password encryption option again in repository settings. if possible can you also send me a video or screenshots of the process.

**Comment by cipitaua** [comment]
Hi. I found the problem: some months ago I changed the encryption password, and the backup files still have the old one. By creating a new repos with the old password I was able to recover. I'm not sure why the problem arised after the update... anyway I solved, thank you for the support and for theis great app.
