### ISSUE TITLE
[Question] Where are Git-managed files stored on the phone?

### ISSUE THREAD

**Issue by kaqqao** [damionx7/Zettel-Notes-Documentation#43]
I have a Git repo configured, works great, but I can't figure out where the files are on my phone.

**Comment by kaqqao** [comment]
It's apparently all packed into a single compressed file

**Comment by damionx7** [comment]
Hey. Its not packed in a single database. The individual note files are stores in private app storage. You can access the internal repository via the mount feature.
To read more follow this link https://znotes.thedoc.eu.org/repository/#mounting-internal-repositories

**Comment by kaqqao** [comment]
Thanks for the response.
I have mounting enabled, but the files are still nowhere to be found. Where should I be looking?

**Comment by damionx7** [comment]
You can share the note as file and then edit that file in any other application. 

Can you please share video of launching zettel notes instead of showing the note files from Files application in android.
