### ISSUE TITLE
[Feature Request] Display non-Markdown files.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#45]
I'd like to be able to open the synchronized non-Markdown files in the native viewers I have assigned to them. Even if they shouldn't be displayed in the application GUI, at least providing access via a `com.android.documentsui` portal is enough. However, I'd like to be able to see them via the application GUI too.

**Comment by damionx7** [comment]
non markdown files are listed in gallery. To access it swipe left navigation drawer, and click on Gallery.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/45#issuecomment-1902069047

Thanks for that, @damionx7. However, that's not particularly useful in most situations because it doesn't display them in the standard directory hierarchy. Additionally, shouldn't the gallery be solely for `image/*.` MIME Types?

**Comment by damionx7** [comment]
Its mainly for media files. And media files are anything apart from note files.

**Comment by damionx7** [comment]
I will add option to toggle directory view in gallery.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/45#issuecomment-1902085785

So it'll look like the standard file list GUI? That's brilliant. Thanks.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/45#issue-2091842526

@damionx7, transferred to https://zettel-notes.canny.io/feature-requests/p/display-non-markdown-files per https://github.com/damionx7/Zettel-Notes-Documentation/issues/48#issuecomment-2057164751.

**Comment by RokeJulianLockhart** [comment]
https://github.com/damionx7/Zettel-Notes-Documentation/discussions/70#discussion-6836176
