### ISSUE TITLE
[Feature Request] Wrap filenames with invalid characters.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#47]
1.	#### **Description**
	
	When a filename is longer than approximately 10 characters, it is truncated. Almost all of my filenames are longer, so I need them to be wrapped instead.
	
1.	#### **Reproduction**
	
	> https://github.com/damionx7/Zettel-Notes-Documentation/issues/47#issuecomment-2041140220

**Comment by damionx7** [comment]
Can you please explain this with one example.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/47#issuecomment-2041076043

@damionx7, cloning https://gitlab.com/rokejulianlockhart/rokejulianlockhart/-/tree/896f10d74bfe0964184c098e27c4876fd8df9fce/%09%60%7Btitle:%20%22Entities%22,%09id:%20%22s1gvg2%22%7D%60%7B.JSON5%7D.dir/%09%60%7Bname:%20%7Bshort:%20%22Beedell.RokeJulianLockhart%22,%09long:%20%7Bthird:%20%22Beedell%22,%09first:%20%22Roke%22%7D%7D,%09id:%20%22s1gvgt%22%7D%60%7B.JSON5%7D.dir/%09%60%7Btitle:%20%22Documents%22,%09id:%20%22s4aaax%22%7D%60%7B.JSON5%7D.dir via https://apkpure.com/zettel-notes-markdown-app/org.eu.thedoc.zettelnotes/download/2.5.0 should demonstrate this.

Specifically, I expect that having invalid filename characters is preventing the normal word wrapping from working, considering that if I create a new file with simple ASCII:

```txt
Placeholder Placeholder Placeholder Placeholder Placeholder
```

it wraps:

> ![image](https://github.com/damionx7/Zettel-Notes-Documentation/assets/42837531/8c7fb5ba-dd63-420a-b6a2-5c67c8f29267)

whereas if I use characters which Zettel would usually automatically convert

```txt
	`{title: "Placeholder Placeholder Placeholder",	id: ""}`{.JSON5}.txt.MD
```

(even on paste, from testing - good input validation there):

> ![image](https://github.com/damionx7/Zettel-Notes-Documentation/assets/42837531/9da1922a-96ea-4fd5-8630-524e30dd3738)

it doesn't wrap:

> ![image](https://github.com/damionx7/Zettel-Notes-Documentation/assets/42837531/3a84855c-0c2f-4dfe-b999-e20acfb765c3)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/47#issue-2227872728

@damionx7, transferred to https://zettel-notes.canny.io/feature-requests/p/wrap-filenames-with-invalid-characters per https://github.com/damionx7/Zettel-Notes-Documentation/issues/48#issuecomment-2057164751.

**Comment by RokeJulianLockhart** [comment]
https://github.com/damionx7/Zettel-Notes-Documentation/discussions/69#discussion-6836175
