### ISSUE TITLE
[Feature Request] Support CSS.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#48]
I utilize CSS for all my documents, like, https://gitlab.com/rokejulianlockhart/rokejulianlockhart/-/blob/dd5bff48df6f7af211b275976d9f1d6a51466103/readMe.MD, in limited but important ways:

1. `<h2>` to `<h6>` inherit their text size from `<p>` (and between them, look identical to each other) because it allows me to utilize them in more versatile manners.
2.  Heading tables don't have a layered line between the `<thead>` and the `<tbody>` in order to allow me to render Markdown tables with (to the viewer) vertical headings.

In order to be able to preview my documents in a useful way, I need to have CSS supported.

**Comment by damionx7** [comment]
Please create feature requests at https://zettel-notes.canny.io/feature-requests. And report any bugs here in this github repository.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/48#issuecomment-2057164751

@damionx7, I'll do so, but some of the issues will be rather broken, considering that (as https://zettel-notes.canny.io/feature-requests/p/support-css#:~:text=%3CblockQuote%3E,%3C%2FblockQuote%3E demonstrates) it doesn't appear to support Markdown. You shall also lose the ability to correlate FRs and bugs using links.
