### ISSUE TITLE
GitHub releases and APK files

### ISSUE THREAD

**Issue by candroid-man** [damionx7/Zettel-Notes-Documentation#49]
I'd love to be able to install Zettel via Obtainium

**Comment by candroid-man** [comment]
Realized this is the repo just for documentation

**Comment by raygervais** [comment]
Following up, is it safe to assume that Zettelnotes is not open source? I cannot find a repo for it anywhere

**Comment by damionx7** [comment]
Yes. Its not open source as of now.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/49#issuecomment-2089114780

@candroid-man, this appears to be utilised as a catch-all issue repository. @damionx7, are you willing to provide APKs via `/releases` in addition to your F-Droid repository? Obtanium is usable via both, but GH Releases can be useful.

**Comment by damionx7** [comment]
F-droid repository is also replicated on gitlab. You can try to use obtanium with it https://gitlab.com/royalhacker/fdroid-live. Uploading on github would be extra work.
