### ISSUE TITLE
[Question] Sync only specific files

### ISSUE THREAD

**Issue by Tredok** [damionx7/Zettel-Notes-Documentation#50]
Is there a way to synchronize specific file type ? For example, sync only md files ? Or md and pdf... ?

**Comment by damionx7** [comment]
Hey. Synchronization works on all files. Its not possible to exclude files from synchronization.

**Comment by damionx7** [comment]
If you want this feature, you can create a new feature request at https://github.com/damionx7/Zettel-Notes-Documentation/discussions.
