### ISSUE TITLE
[Feature Request] Add Nextcloud repository synchronization support.

### ISSUE THREAD

**Issue by rokejulianlockhart** [damionx7/Zettel-Notes-Documentation#8]
Dropbox is fine, but I prefer Nextcloud for obvious reasons.

I understand that `git` mostly fits this niche currently, but although `git` is superior for code files, it's not really needed for text files, since the Nextcloud protocol provides support for simultaneous modification of text files too.

I'm mostly requesting OAuth authentication for NC, since https://t.me/c/1571773822/4944 states that Zettel already supports `webdavs://`.

![https://t.me/c/1571773822/4951](https://t.me/c/1571773822/4951)

**Comment by damionx7** [comment]
Hey. Its is in my todo list.

**Comment by damionx7** [comment]
You can use webdav for nextcloud synchronization. See this post for more details.
https://t.me/zettelnotes/138
