### ISSUE TITLE
[Feature Request] Don't automatically increase number when typing new entry in list if preceded by two or more `0.`s.

### ISSUE THREAD

**Issue by rokejulianlockhart** [damionx7/Zettel-Notes-Documentation#9]
When typing numbered lists, I tend to use
```markdown
0. entry
0. entry
0. entry
```
rather than
```markdown
0. entry
1. entry
2. entry
```
because most markdown processors automatically number the list, as Zettel does. However, when making these lists, when I press enter to add a new line, Zettel helpfully automatically creates a `1.`. I don't want this, because my lists is obviously supposed to be automatically numbered.

Consequently, if the list already contains 2 or more `0.`s, Zettel should put another `0.` instead of a `1.`.

**Comment by damionx7** [comment]
Sure. I will add a settings option for this.
