### ISSUE TITLE
Performance regression while text is in a RTL language and line numbering is On

### ISSUE THREAD

**Issue by chromer030** [damionx7/Zettel-Notes-Documentation#92]
In RTL markdown notes (Persian, Arabic), if you turn on line numbering, the scrolling performance in edit mode would be worst.

1- Turn on line numbering in Settings
2- Open a long RTL-language note
3 - try to scroll note

In same file turning off line numbering, bring back smoothness of scrolling.

**Comment by damionx7** [comment]
Hey! Can you try updating the app (v2.6.0) and see if this issue exists. 

I have updated the app on f-droid for now. https://thedoc.eu.org/fdroid/repo/zettel-notes-20600.apk.

**Comment by chromer030** [comment]
Tested 2.6.0 and fixed, thank you.

Another minor issue is status bar color change:

![Screenshot_20240620-214009_Zettel_Notes_1](https://github.com/damionx7/Zettel-Notes-Documentation/assets/13361552/e103ef5f-d905-4d36-ad92-0150a1216e91)

QuickEdit app:

![Screenshot_20240620-215040_QuickEdit+_1](https://github.com/damionx7/Zettel-Notes-Documentation/assets/13361552/8d0681e8-825c-4ca3-a055-3329ed9ba4ac)

**Comment by damionx7** [comment]
You are most welcome.

This status bar color change is intentional. Do you want same color for toolbar and status bar ?

**Comment by chromer030** [comment]
You are great man.

Could it be an option in Settings to enable/disable status bar color change?

I would like seamless view of app while all colors are in shape and order.

**Comment by chromer030** [comment]
Another somehow annoying issue:

In RTL-Languages texts, scrollbar covers the first characters of notes:

https://github.com/damionx7/Zettel-Notes-Documentation/assets/13361552/050fe6b6-8911-4f47-84d7-57dbf9f7cb4b

I tried : Note Margin > Right > 16
But yet it covers first character
A better solution would be best ...

**Comment by chromer030** [comment]
Another minir issue:

Customized Text color reverts to white (default).

1- Changing Text color and selecting theme (Cyberpumk in my case)
2- Came back to note without closing app, text color is changed and OK.
2- But after closing and reopening the app, note is in white not selected color!

**Comment by damionx7** [comment]
I will consider try to fix these issues.

**Comment by damionx7** [comment]
> Another minor issue:
> 
> Customized Text color reverts to white (default).
> 
> 1- Changing Text color and selecting theme (Cyberpumk in my case) 2- Came back to note without closing app, text color is changed and OK. 2- But after closing and reopening the app, note is in white not selected color!

I can't replicate this issue. Can you please share a video. It would help in solving this issue.

**Comment by damionx7** [comment]
> Another somehow annoying issue:
> 
> In RTL-Languages texts, scrollbar covers the first characters of notes:
> 2024_06_24_22_57_25_trim.mp4
> rec.mp4
> 
> I tried : Note Margin > Right > 16 But yet it covers first character A better solution would be best ...

I have added settings option in `Settings > Editor and Viewer` to change scrollbar size.

**Comment by chromer030** [comment]
> I can't replicate this issue. Can you please share a video. It would help in solving this issue.

I solved it by creating new theme and not editing current one, issue happens when we edit current default themes, the edited colors doesnt apply after two times reopening of app.

We can ignore this, creating new theme with desired colors is solution.
