### ISSUE TITLE
'Scanning Gallery...' while background sync is off

### ISSUE THREAD

**Issue by chromer030** [damionx7/Zettel-Notes-Documentation#93]
While background sync is off and app usage is completely offline, there is always an annoying notification : scanning gallery!

Please define options to manually enable/disable sync/scans and app's components like gallery etc...

Thanks in advance.

**Comment by damionx7** [comment]
Hey! To disable this notification. Go to Andoroid settings for Zettel Notes > Manager Notifications > Gallery Scanner. And then toggle Allow notifications.
